version: '3.3'
services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432

  bot:
    build: ./
    restart: always
    env_file: .env
    depends_on:
      - db
    command: sh -c "python3 manage.py makemigrations --no-input &&
                    python3 manage.py makemigrations --merge --no-input &&
                    python3 manage.py migrate &&
                    python3 manage.py createsuperuser --no-input || true &&
                    python3 bot.py"

volumes:
  db_data: