# Generated by Django 4.2.5 on 2023-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
