# Generated by Django 4.2.6 on 2023-10-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_chat_id_alter_chat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Статус онлайна пользователя'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='Отправляли уведомление'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID чата в телеграмме'),
        ),
    ]
