# Generated by Django 4.2.6 on 2023-10-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_is_online_chat_is_send_alter_chat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Статус онлайна пользователя'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='Отправляли уведомление'),
        ),
    ]
