# Generated by Django 4.2.6 on 2023-10-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chat_is_online_alter_chat_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Статус онлайна пользователя'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='Отправляли уведомление'),
        ),
    ]
